version: "3.8"

services:
  db:
    image: postgres:latest
    container_name: crossposthub_db
    ports:  
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: crossposthub  
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/usr/src/app  # useful in dev mode
    restart: unless-stopped
    
    depends_on:
      - db
